In [ ]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.tokenize import word_tokenize

text = "I love NLP."

tokens = word_tokenize(text)

print(tokens)

['I', 'love', 'NLP', '.']


In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

words = ["I","am","learning","NLP"]

filtered = [w for w in words if w.lower() not in stop_words]

print(filtered)

['learning', 'NLP']


In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

print(stemmer.stem("playing"))
print(stemmer.stem("studies"))

play
studi


In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("Apple is looking at buying a startup.")

for token in doc:
    print(token.text, token.lemma_)

Apple Apple
is be
looking look
at at
buying buy
a a
startup startup
. .


In [ ]:
import re
import string
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download resources (run once)
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

text = "Hello!!! My name is Saksham. I LOVE learning NLP in 2026."

# Lowercase
text = text.lower()

# Remove numbers
text = re.sub(r"\d+", "", text)

# Remove punctuation
text = text.translate(str.maketrans("", "", string.punctuation))

# Tokenize
tokens = word_tokenize(text)

# Remove stop words
stop_words = set(stopwords.words("english"))
tokens = [word for word in tokens if word not in stop_words]

# Lemmatize
lemmatizer = WordNetLemmatizer()
tokens = [lemmatizer.lemmatize(word, pos="v") for word in tokens]

print(tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...


['hello', 'name', 'saksham', 'love', 'learn', 'nlp']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love NLP",
    "I love Python",
    "Python loves AI"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['ai' 'love' 'loves' 'nlp' 'python']
[[0 1 0 1 0]
 [0 1 0 0 1]
 [1 0 1 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

docs = [
    "I love NLP",
    "I love Python",
    "Python is great"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(docs)

print(X.toarray())

[[0.         0.         0.60534851 0.79596054 0.        ]
 [0.         0.         0.70710678 0.         0.70710678]
 [0.62276601 0.62276601 0.         0.         0.4736296 ]]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

A = np.array([[1, 2, 3]])
B = np.array([[2, 4, 6]])

print(cosine_similarity(A, B))

[[1.]]
